[package]
name = "nacos-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = "1.0.130"
serde_derive = "1.0.130"


[target.x86_64-unknown-linux-musl]
linker = "rust-lld"